### ISSUE TITLE
Label/Relationship filter while loading the Graph

### ISSUE THREAD

**Issue by Shaficks** [neo4j-contrib/neo4j-graph-algorithms#147]
The **_UnionFindStream()_** procedure allows to load either allNodes or only one type of nodes and allRelationships or only one type of relationships.
The main purpose here is to make possible loading the graph while ignoring some Label(s) and Relationship type(s).
The procedure uses the **_HeavyGraphFactory.build()_** method, which uses methods from **_ReadOperations_** class. 
First option is to edit the procedure itself, second option is to add another procdure that takes 2 List<String> parameters that represent respectively the list of Labels and Relationship types to ignore. The third parameter will be the config map like the original procedure.  

Another option proposed by Michael is to implement a label and relationship-filter similar to the apoc one : 
Follow  this link for more info : https://neo4j-contrib.github.io/neo4j-apoc-procedures/#_path_expander

**Comment by mknblch** [comment]
Since Cypher is the right tool to do selects on the graph data we decided to load either one or all relationships in the Heavy/Light/Kernel Graph impl.. 

To load subsets of nodes you can try @jexp 's `org.neo4j.graphalgo.core.heavyweight.HeavyCypherGraphFactory` which evaluates cypher statements for node and relationships. Another obvious way would be to assign a new label to your node-set. :)

**Comment by mneedham** [comment]
You could also define which nodes and relationships you want to run algorithms on by using Cypher projections. 

See: https://github.com/neo4j-contrib/neo4j-graph-algorithms/tree/3.3#cypher-projections

I'll close this as I think that will solve the issue but feel free to open it again if not.
