### ISSUE TITLE
Shortest path along one relationship type

### ISSUE THREAD

**Issue by arnaud-m** [neo4j-contrib/neo4j-graph-algorithms#152]
The last call of the following code snippet returns an invalid answer.
Indeed, the shortest path follows ROAD **and** RAIL relationships whereas it should only follow ROAD ones. 
```
  // Test Dijsktra algorithms

  // Generate a small graph
CREATE (a:Loc{name:'A'}), (b:Loc{name:'B'}), (c:Loc{name:'C'}), (d:Loc{name:'D'}), (e:Loc{name:'E'}), (f:Loc{name:'F'}),
       (a)-[:ROAD {d:50}]->(b),
       (a)-[:ROAD {d:50}]->(c),
       (a)-[:ROAD {d:100}]->(d),
       (a)-[:RAIL {d:50}]->(d),
       (b)-[:ROAD {d:40}]->(d),
       (c)-[:ROAD {d:40}]->(d),
       (c)-[:ROAD {d:80}]->(e),
       (d)-[:ROAD {d:30}]->(e),
       (d)-[:ROAD {d:80}]->(f),
       (e)-[:ROAD {d:40}]->(f),
       (e)-[:RAIL {d:20}]->(f);
       
  // Test Apoc Dijsktra
MATCH (o:Loc{name:'A'}), (d:Loc{name:'F'}) 
      CALL apoc.algo.dijkstra(o,d,'ROAD>', 'd') yield path, weight
RETURN path, weight;

       // Test Apoc Dijsktra
MATCH (o:Loc{name:'A'}), (d:Loc{name:'F'}) 
      CALL apoc.algo.dijkstra(o,d,'ROAD>|RAIL>', 'd') yield path, weight
RETURN path, weight;

       // GraphAlgo Dijsktra Stream. NOT WORKING ?
MATCH (from:Loc{name:'A'}), (to:Loc{name:'F'})
      CALL algo.shortestPath.stream(from, to, "d", {label:'Loc', relationship:'ROAD', defaultValue:1.0})
//      CALL algo.shortestPath.stream(from, to, "d", {label:'Loc', relationship:'ROAD>', defaultValue:1.0})
      yield nodeId, cost
return nodeId, cost
```

I have asked to the slack channel and no one has detected a syntax error.

In the mean time, I would like to ask an advice to implement a variant of the Bellman-Ford algorithm.
Should I use the APOC Traverser or your (deprecated) Graph interface ?

Thanks for your help.

**Comment by mknblch** [comment]
Thanks for your feedback. I will test tomorrow if we have a bug. 

--

The graph interface is just a composition of other interfaces (which are not deprecated). So it's up to you, if you need all features of Graph you can use it like we did in most of the algorithms. But you can also pick the functionality you need from `org.neo4j.graphalgo.core.sources`. An example can be found in `org.neo4j.graphalgo.MSTPrimProc`. Unfortunately we lack of having jdoc so the highlvl api may still be the best option.

**Comment by arnaud-m** [comment]
Thank you for your answer. 

If I understand well, your goal is to remove the Graph interface and instead build the required sub-interface on demand. 
I am going to look at the at the MSTPrimProc. If it looks too complicated, I will use the graph interface.

**Comment by mknblch** [comment]
I tested `algo.shortestPath.stream` with your Testdata and the following query: 

`MATCH (from:Loc{name:'A'}), (to:Loc{name:'F'}) CALL algo.shortestPath.stream(from, to,'d', {label:'Loc', relationship:'ROAD', defaultValue:999999.0}) YIELD nodeId, cost with nodeId, cost MATCH(n) WHERE id(n) = nodeId RETURN n.name as name, cost"`

At first: We have an error in the description. It should be **relationshipQuery** or **nodeQuery** instead of **relationship** and **label**. This is due to our refactoring in ProcedureConfiguration - we forgot to adapt the description :( 

The query from above leads to the following result:

  "n"         │"cost"
│{"name":"A"}│0   
│{"name":"D"}│50   
│{"name":"E"}│80   
│{"name":"F"}│100  
│{"name":"F"}│0    
│{"name":"F"}│0    
│{"name":"A"}│0    
│{"name":"D"}│50   
│{"name":"E"}│80   
│{"name":"F"}│100  

This is kinda strange since the result looks partialy right (from A-F). I adapted the Query into a UnitTest which yields _A:0.0->D:50.0->E:80.0->F:100.0;_ So it seems we also have an error in the **resultStream()** logic where the raw-double[] gets converted into a Stream.

The results from the unit test using the adapted Query leads to:

A:0.0
C:50.0
D:90.0
E:120.0
F:160.0

or for ROAD + RAILS (any relationship) yields:

A:0.0
D:50.0
E:80.0
F:100.0

Thanks for your help @arnaud-m  im going to fix this

**Comment by arnaud-m** [comment]
Thank you for your quick answers.

**Comment by mneedham** [comment]
Docs and code are both fixed for this so closing.
