### ISSUE TITLE
for procedures that own the graph-impl release it before write and only keep idmap

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/neo4j-graph-algorithms#217]
to free memory that might be needed for the tx commit

i.e. if a procedure loaded a graph itself, 
it should call a release/dispose method on the graph to release internal resources like adj-matrix
and only keep id-map and computed scores around

**Comment by knutwalker** [comment]
We could have methods on the Graph interface: `IdMapping idMapping()` and `BatchIterable batchIterable()`. Where the implementations allow this, the graph could return the id map, otherwise it could return itself.
In the exporting step, we use those references and null the ref to the graph in the proc. If the proc was the only one that has been using the graph, it's now free to be collected. If the graph is being used elsewhere (e.g. due to #200, #201), no collection can happen yet, but also the graph is still usable for other procedures.
