### ISSUE TITLE
Could you explain algo.louvain's write back result ?

### ISSUE THREAD

**Issue by mengjiaowang** [neo4j-contrib/neo4j-graph-algorithms#740]
Hello, I use algo.louvain to detect communities in my graph, I set write equals to true and writeProperty equals to 'community' so that the procedure writes results back. After the procedure is done, I find that the 'community' property is a 3D array, while, in all the examples I could find in official document, louvain will write an integer back, indicating the community id. Could you explain what the numbers in result array mean. For my case, I got the following result:

[1,1,1]
[2,2,2]
[3,3,3]
...
[1234,1235,1236]

for some vertex, all the elements in array are the same, but some vertex are not equal to each other.

Thanks a lot!

**Comment by mneedham** [comment]
Hey,

Sorry yeh that documentation needs updating as we've added the 2nd phase of the Louvain algorithm since it was written.

@tomasonjo has written a blog post that explains it pretty well - https://tbgraph.wordpress.com/2018/10/15/discovering-hiearchical-community-structure-in-got-world-using-louvain-algorithm-and-neo4j/

Let me know if that helps.

Cheers, Mark
