### ISSUE TITLE
ArrayIndexOutOfBoundException when running Louvain algorithm

### ISSUE THREAD

**Issue by amine-ben** [neo4j-contrib/neo4j-graph-algorithms#746]
Hi all,

When executing the [Louvain algorithm][1] from the neo4j-graph-algorithms, I run into the following error.  
```
 Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `algo.louvain.stream`: Caused by: java.lang.ArrayIndexOutOfBoundsException: 2409421
```
I must also point out that the value right after the exception changes slightly (+/- 1000) from one execution to another. Is this normal?
Moreover, setting up the algorithm's parameter '**graph**' to '*huge*' also resulted in the same error.  

Here is the Cypher query I am using,  

` CALL algo.louvain.stream('${Label}', '${rel}', {graph : 'huge', concurrency : 4}) YIELD nodeId, community`
   

Below some characteristics of the environment: 

 - neo4j-community-3.4.4
 - graph-algorithms-algo-3.4.4.0
 - apoc-3.4.0.1-all
 - dbms.memory.heap.initial_size=512m
 - dbms.memory.heap.max_size=8G
 
Graph characteristics:
 - 2.4M nodes
 - 10M edges

Thank you in advance for any pointers on how to solve this issue.

kind regards,

 
  [1]: https://neo4j.com/docs/graph-algorithms/current/algorithms/louvain/

**Comment by amine-ben** [comment]
Hi all, 

The issue has been resolved in the latest version: graph-algorithms-algo-3.5.0.1

Greetings to @mneedham for pointing this out in the following stack overflow [question](https://stackoverflow.com/questions/52949841/arrayindexoutofboundsexception-when-running-neo4j-graph-algo-louvain/52986054#52986054).

Kind regards,

**Comment by chencjiajy** [comment]
when I use  the environment:

neo4j-community-3.3.1
graph-algorithms-algo-3.3.5.0

when I running Louvain algorithm, I met:

`Failed to invoke procedure `algo.louvain`: Caused by:java.lang.ArrayIndexOutofBoundsException:102753`

`Unknown function 'algo.getNodeById' ` as I use the example as [doc](https://neo4j.com/docs/graph-algorithms/3.4/algorithms/louvain/)

**But, when I use the environment:**
neo4j-community-3.3.1
graph-algorithms-algo**-3.5.0.1**

when I running Louvain algorithm, I met:
`Louvain: Failed to invoke procedure `algo.louvain`: Caused by: java.lang.NoClassDefFoundError: org/neo4j/internal/kernal/api/exceptions/KernelException`

the [issue 512](https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/512) said need to match db version ,so I **change** graph-algorithms version to 3.3.5.0

> Yes you need to use the right version for your db version

so how I can fix this problem @amine-ben @mneedham 

Best regards
