### ISSUE TITLE
Update algos.list() to return functions as well as procedures

### ISSUE THREAD

**Issue by denniskorablev** [neo4j-contrib/neo4j-graph-algorithms#831]
The whole group of linkprediction algorithms is missing in 3.5.3.2 as well as 3.3. Is this happening on purpose? How can I install algo.linkprediction.adamicAdar if not from the 3.5 or 3.3 (tried both).

Thank you.

**Comment by mneedham** [comment]
Hey,

This isn't in 3.3, but it is in 3.4.* and 3.5.*

The first releases that have these functions are:

3.4.12.2 and 
3.5.3.0

We also have release notes for each one over here - https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases

These are functions rather than procedures, so check `CALL dbms.functions()` to see if they are there?

**Comment by denniskorablev** [comment]
Thanks, functions vs algos was the main thing. Your Readme explicitly saying to check `CALL algo.list()` to see the full list. I suggest to give more details about `CALL dbms.functions()` as an option.

**Comment by mneedham** [comment]
Good point, we'll add them to that procedure. I'll keep this open until that's done

**Comment by mneedham** [comment]
This is done on this commit -https://github.com/neo4j-contrib/neo4j-graph-algorithms/commit/fac8cdc9a4d41ef2e859984aab006580161249b8

Will release that some time this week hopefully

**Comment by mneedham** [comment]
This is released

**Comment by Siraj1munir** [comment]
Hi mark! I have installed Graph algo package in neo4j desktop but after running the mentioned commands I can't see algo.linkprediction algorithms is this any issue at my end or any update is going on?
![error](https://user-images.githubusercontent.com/16990235/55859972-9ed7c280-5b8c-11e9-9027-9fb1429b499a.PNG)
Plus due to some bug in latest release I'm unable to go online and reinstall package
