### ISSUE TITLE
algo.memrec appears to be missing from 3.5.4.0

### ISSUE THREAD

**Issue by Dcanzano** [neo4j-contrib/neo4j-graph-algorithms#905]
With Neo4j 3.5.5 and ALGO 3.5.4.0 running 

````
call dbms.procedures() yield name as n1 where n1 starts with 'algo' return n1 order by n1;
````

yields results similar to

````
| "algo.kShortestPaths.stream"             |
| "algo.labelPropagation"                  |
| "algo.labelPropagation.stream"           |
| "algo.list"                              |
| "algo.louvain"                           |
| "algo.louvain.stream"                    |
| "algo.mst"                               |
| "algo.pageRank"                          |
| "algo.pageRank.stream"                   |
| "algo.randomWalk.stream"                 |
| "algo.scc"                               |
| "algo.scc.forwardBackward.stream"        |
````

note there is no algo.memrec eventhough documentation says it exists at https://neo4j.com/docs/graph-algorithms/3.5/projected-graph-model/memory-requirements/?_ga=2.241186698.949873385.1563187916-483926203.1547652688#algo-memrec-procedure

request the procedure be returned or the documentation be updated

**Comment by jjaderberg** [comment]
The memory recommendation features were added recently, try updating the plugin and rerunning the query.
Like other Neo4j documentation, the graph algorithm docs are granular to `major.minor` version. Normally this is not a cause of confusion because we don't usually add features in patch releases (or stitch releases for that matter). But with the recent ramp up of work on the algorithms we have been doing precisely that. This means some aspects of the 3.5 documentation may not apply to older 3.5.x.x versions of the algorithms. This is regrettable, and should go away as we stabilize on new API (or, if necessary, decide to change the versioning scheme).

**Comment by bgreenlee** [comment]
Which branch should I use to build the jar? Master? The latest commit to the 3.5 branch is April 18. The 3.5.0.4 jar is from April 10, and looks like the 13 commits from 3.5 not in that jar are mostly doc changes.

**Comment by Dcanzano** [comment]
@bgreenlee  to confirm and perhaps i may have started this and have corrected where approrpriate but to confirm this is ALGO 3.5.4.0 and not 3.5.0.4.  Correct?
The jar i have in place where i can reproduce is graph-algorithms-algo-3.5.4.0.jar

**Comment by bgreenlee** [comment]
Confirmed it is 3.5.4.0. I downloaded it from https://github.com/neo4j-contrib/neo4j-graph-algorithms/releases

**Comment by bgreenlee** [comment]
Confirming that it works in 3.5.4.7, obtained from http://s3-eu-west-1.amazonaws.com/com.neo4j.graphalgorithms.dist/neo4j-graph-algorithms-3.5.7.0-standalone.jar. That version is not listed in the releases section of this repository however. Thank you @Dcanzano!

**Comment by bgreenlee** [comment]
Could you tell me where the code for 3.5.7.0 lives? I'm not seeing it in this repository.

**Comment by Mats-SX** [comment]
@bgreenlee It is currently not open source, but we will re-host the sources under a new location soon. Stay tuned!

**Comment by AliciaFrame** [comment]
Currently the most up to date graph algos releases are hosted on our downloads center page: https://neo4j.com/download-center/
